version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    container_name: url-shortener-postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  redis-stack-server:
    image: redis/redis-stack-server:latest
    container_name: url-shortener-redis
    ports:
      - "6379:6379"
